#!/bin/bash

set -e
set -o pipefail

script_msg()
{
    echo -e "--- ${*} ---"
}

fatal_error() {
    script_msg "\tFATAL ERROR: ${*}" >&2
    exit 1
}

###

if [ -n "$1" ]; then
    crontracker_log_path="$1"
else
    fatal_error "usage: crontracker CRONTRACKER_LOG_PATH"
fi

# Make crontracker_log_path if it doesn't exist
if [ ! -d "$crontracker_log_path" ]; then
    mkdir -p "$crontracker_log_path"
fi

# cd there so that we don't have to worry about paths as much
cd "$crontracker_log_path" || fatal_error "Failed to cd to $crontracker_log_path"

# If we aren't in a git repo, initialize one
if [ ! -d ".git" ]; then
    git init
    crontab -l > crontabs.txt
    git add crontabs.txt
    git commit -m "Initial version of crontabs.txt"
    # Exit here; no sense in continuing since there can't be any diffs
    echo "Successfully initialized $crontracker_log_path; exiting"
    exit 0
fi

# If crontabs.txt has local modifications then that means something else has changed
# it. Bail out here since we don't know why that has happened
if ! git diff --quiet -- crontabs.txt; then
    fatal_error "ERROR: crontabs.txt has been locally modified! Bailing out; this will need to be fixed by hand!"
fi

# Dump the current crontab
crontab -l > crontabs.txt

# If it is different than it was before, commit the changes
if ! git diff --exit-code -- crontabs.txt; then
    script_msg "${USER}@${HOSTNAME}'s crontab has been changed; committing changes"
    last_modified="$(git log -1 --format=%cd -- crontabs.txt)" || fatal_error "Could not detect last modification of crontabs.txt"
    git add -- crontabs.txt || fatal_error "Failed to add crontabs.txt"
    git commit -m "\"Update to crontabs.txt detected; last modified at $last_modified\"" || fatal_error "Failed to commit changes to crontabs.txt"
fi
